### ISSUE TITLE
Can't get user

### ISSUE THREAD

**Issue by nwicakson** [reactql/example-auth#5]
I'm new using reactql, but wanna try it for my work.
obj.session.jwt() is done, but I cant get obj.session.getUser().

```
TypeError: obj.session.getUser is not a function
    at user (/Users/nwicakson/Documents/TA/informatics-reactql/dist/server_dev.js:3702:43)
    at resolveFieldValueOrError (/Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:498:12)
    at resolveField (/Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:462:16)
    at /Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:311:18
    at Array.reduce (<anonymous>)
    at executeFields (/Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:308:42)
    at collectAndExecuteSubfields (/Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:746:10)
    at completeObjectValue (/Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:728:10)
    at completeValue (/Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:625:12)
    at /Users/nwicakson/Documents/TA/informatics-reactql/node_modules/graphql/execution/execute.js:582:14
    at <anonymous
```

**Comment by leebenson** [comment]
Did you make any changes to the code?

**Comment by nwicakson** [comment]
yeah, a lot. I used reactql and then connected it to wordpress like this guy's doing
https://github.com/ramsaylanier/WordExpress.
Then, I add login (without facebook) just like example-auth. But still get error at that obj.session.getUser().

**Comment by leebenson** [comment]
I'd need to see your code to figure out what's going on. Please post a link to a git repo.

**Comment by nwicakson** [comment]
https://github.com/nwicakson/informatics-reactql
sorry, my code is really messed up

**Comment by leebenson** [comment]
I'd like to help, but unfortunately don't have the free time to debug large-scale code changes. Hopefully you've figured it out by now.

**Comment by samparmenter** [comment]
I might be wrong but you haven't created a getUser function on the Session.prototype in this project as far as I can see. Thats just from pulling down the code without changing anything.

**Comment by nwicakson** [comment]
@samparmenter yeah, you are right. Thank you for the help, really. At that time, I hadn't created getUser() function. I have done it with this line code:
`user(obj) {
        return obj.user && obj.user.id && Connectors.getUser(obj.user.id);
      },`
