### ISSUE TITLE
build-static broken

### ISSUE THREAD

**Issue by bdombro** [reactql/example-auth#7]
I am exploring reactql and try to run build-static, but it doesn't work. It says it can't find static.js.

Log:
```
$ npm run build-static

> @2.9.5 build-static /Users/briandombrowski/Work/Development/ReactQL/example-base
> cross-env NODE_ENV=production WEBPACK_CONFIG=static webpack --colors

Error: static.js not found or has errors:
{ Error: Cannot find module '/Users/briandombrowski/Work/Development/ReactQL/example-base/node_modules/node-zopfli/lib/binding/node-v51-darwin-x64/zopfli.node'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/briandombrowski/Work/Development/ReactQL/example-base/node_modules/node-zopfli/lib/zopfli.js:7:14)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/briandombrowski/Work/Development/ReactQL/example-base/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/briandombrowski/Work/Development/ReactQL/example-base/node_modules/zopfli-webpack-plugin/dist/index.js:17:19)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/briandombrowski/Work/Development/ReactQL/example-base/node_modules/babel-register/lib/node.js:152:7) code: 'MODULE_NOT_FOUND' }
```

**Comment by igo** [comment]
Obviously zopfli package was not installed properly. Sometimes it needs to be compiled on your computer. Rerun npm install and fix errors.

**Comment by leebenson** [comment]
`npm rebuild` should help fix any lib/binary compilation issues, too.
